[book]
authors = ["Spirited"]
language = "en"
multilingual = false
src = "src"
title = "Conquer Online Development Wiki"

[output.html]
git-repository-url = "https://github.com/conquer-online/wiki"
git-repository-icon = "fa-github"
default-theme = "rust"
preferred-dark-theme = "ayu"
site-url = "/wiki/"

[output.html.fold]
enable = true
level = 1